### PR TITLE
Load TOC from branches and releases

### PR DESCRIPTION
**Pull request by mikemurray**
ReDoc how loads the TOC from branches and releases (tags)

Updates
- Adds all branches to brach select
- Adds Releases to branch select
- pre-fetch `publicBranches` from settings file. Usually `master` and `development`
- Do not blindly clear the doc cache. Only non-release docs get cache cleared on cron.
- Release docs are cached permanently as they would mostly likely never change.

### CODE REVIEW

**Comment by mikemurray** [comment]
Issues with the duplication should be resolved.

**Comment by aaronjudd** [comment]
👍  I've created a new issue in #60, to have the defaults load from redoc when no settings are load.

**Comment by aaronjudd** [comment]
@jshimko is going to take care of the docker build error in CI, then this is good go...

**Comment by jshimko** [comment]
Docker fixes ready to go at https://github.com/reactioncommerce/redoc/pull/61

**Comment by aaronjudd** [comment]
@jshimko 👍  thanks! merging....

**Pull request merged**
