### PR TITLE
Load toc from repository

### PR DESCRIPTION
**Pull request by marceloschmidt**
With this PR, Redoc will fetch the TOC from the repository folders and files structure when tocData doesn't exist, i.e., remove the `tocData` section from the `private/redoc.json` or the `initialRepoData`. Ex.: 
```
{
  "repos": [{
    "org": "RocketChat",
    "repo": "Rocket.Chat.Docs",
    "label": "Rocket.Chat Docs",
    "description": "Rocket.Chat Documentation"
  }]
}
```

The Redoc will mirror GitHub structure. Each folder becomes a main nav item. Each .md file becomes a sub-nav item. If the folder contains a README.md, this becomes the content for the main item.

image

image

### CODE REVIEW

**Comment by aaronjudd** [comment]
:+1:  looks like it should work with multiple repos as well..    we've been talking about an ignore setting as well, and @mikemurray is adding a publishing admin right now so this should work nicely with that functionality..

**Comment by jshimko** [comment]
:+1:

Can we maybe grab that `underscorestring:underscore.string` directly from NPM though?  Now that we're using 1.3, we're generally trying to use NPM instead of Atmosphere whenever it's an option.  

https://www.npmjs.com/package/underscore.string

**Comment by marceloschmidt** [comment]
Ah, nice catch! Yes, let me do this and update this PR. I'll also include restivus for auto-updating via webhooks whenever the repository changes.

**Comment by marceloschmidt** [comment]
With the latest commit, if configured, every time someone updates the docs repository github will make an api call to update the docs, thus removing the need for manual or crond updates.

**Pull request merged**
